import {
  Bot,
  Settings,
  Mail,
  Lock,
  LogOut,
  ChevronLeft,
  Plus,
  X,
  PhoneCall,
  PlayCircle,
  PauseCircle,
  Volume2,
  VolumeX,
  Calendar,
  AudioLines,
  CheckCircle,
  FileSpreadsheet,
  Mic,
  Square,
  Upload,
  Trash,
  type Icon as LucideIcon,
  type LucideProps,
  History,
  ChevronDown,
  ChevronUp,
  File,
  ChevronRight,
  Clock,
  ChartBar,
  Loader2,
  MoreHorizontal,
  Download,
  Volume,
  Volume1,
  CreditCard,
  Book,
  BookOpen,
  FileText,
  Image,
  Link,
  FileImage,
  VolumeIcon,
  Expand,
  CalendarPlus,
  PlusCircle,
  Activity,
  RefreshCcw,
  ScatterChart,
  AlertCircle,
  AlignLeft,
  Loader2Icon,
  RefreshCw,
  Layers,
  UploadCloud,
  Save,
  Edit2,
  Trash2,
  Globe,
  ExternalLink,
  HelpCircle,
  MessageCircle,
  MapPin,
  MessageSquare,
  Bell,
  BellOff,
  Check,
  Copy,
  Table,
  CircleFadingArrowUp,
  Phone,
  CircleCheck,
  Pencil,
  ArrowLeft,
  Eye,
  Webhook,
  Folder,
  FolderPlus,
  Edit,
  RotateCw,
  Users,
  XCircle,
  Inbox,
  TrendingUp,
  Info,
  Pin,
  HelpCircleIcon,
  DatabaseIcon,
  CheckCircleIcon,
  Zap,
  Play,
  Lightbulb,
  ArrowRight,
  Search,
  LightbulbIcon
} from 'lucide-react';
import { memo } from 'react';

const IconComponents: Record<string, typeof LucideIcon> = {
  bot: Bot,
  settings: Settings,
  mail: Mail,
  lock: Lock,
  logOut: LogOut,
  chevronLeft: ChevronLeft,
  plus: Plus,
  x: X,
  'tasks-checked': CheckCircle,
  'phone-call': PhoneCall,
  'playCircle': PlayCircle,
  'pauseCircle': PauseCircle,
  'volumeUp': Volume2,
  'volume-mute': VolumeX,
  'volume-low': Volume,
  'volume-medium': Volume1,
  'fileSpreadsheet': FileSpreadsheet,
  'mic': Mic,
  'upload': Upload,
  'square': Square,
  calendar: Calendar,
  'trash': Trash,
  'history': History,
  'chevronDown': ChevronDown,
  'chevronUp': ChevronUp,
  'file': File,
  'chevronRight': ChevronRight,
  'clock': Clock,
  'chart-bar': ChartBar,
  'spinner': Loader2,
  'moreHorizontal': MoreHorizontal,
  'download': Download,
  'credit-card': CreditCard,
  'book': Book,
  'book-open': BookOpen,
  'file-text': FileText,
  'image': Image,
  'link': Link,
  'file-image': FileImage,
  'volume-up': Volume2,
  'expand': Expand,
  'loader2': Loader2,
  'calendar-plus': CalendarPlus,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'plus-circle': PlusCircle,
  'activity': Activity,
  'refresh-ccw': RefreshCcw,
  'scatter-chart': ScatterChart,
  'alert-circle': AlertCircle,
  'align-left': AlignLeft,
  'loader-2': Loader2Icon,
  'refresh-cw': RefreshCw,
  'layers': Layers,
  'upload-cloud': UploadCloud,
  'save': Save,
  'edit-2': Edit2,
  'trash-2': Trash2,
  'globe': Globe,
  'external-link': ExternalLink,
  'help-circle': HelpCircle,
  'message-circle': MessageCircle,
  'map': MapPin,
  'message-square': MessageSquare,
  'bell': Bell,
  'bell-off': BellOff,
  'check': Check,
  'copy': Copy,
  'table': Table,
  'audio-lines': AudioLines,
  'circle-fading-arrow-up': CircleFadingArrowUp,
  'phone': Phone,
  'circle-check': CircleCheck,
  'pencil': Pencil,
  'left-arrow': ArrowLeft,
  'eye': Eye,
  'webhook': Webhook,
  'folder': Folder,
  'folderPlus': FolderPlus,
  "edit": Edit,
  'rotate-cw': RotateCw,
  'users': Users,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'inbox': Inbox,
  'trending-up': TrendingUp,
  'info': Info,
  'pin': Pin,
  'help': HelpCircleIcon,
  'database': DatabaseIcon,
  'checkCircle': CheckCircleIcon,
  'zap': Zap,
  'play': Play,
  'lightBulb': Lightbulb,
  'arrowRight': ArrowRight,
  'trendingUp': TrendingUp,
  'xCircle': XCircle,
  'search': Search,
  'lightbulb': LightbulbIcon
};

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: keyof typeof IconComponents;
}

export const Icon = memo(function Icon({ name, ...props }: IconProps) {
  const IconComponent = IconComponents[name];
  if (!IconComponent) {
    console.error(`Icon "${name}" not found`);
    return null;
  }
  return <IconComponent {...props} />;
})